Repository logstash-plugins/logstash-input-elasticsearch, pull requests merged in 2024-12, with the labels that each got.

#211 Set x-elastic-product-origin header for ES requests
  CHANGELOG.md
  lib/logstash/inputs/elasticsearch.rb
  logstash-input-elasticsearch.gemspec
  spec/inputs/elasticsearch_spec.rb
Labels: status:approved

#213 Remove deprecated SSL settings and simplify SSL configuration
  CHANGELOG.md
  docs/index.asciidoc
  lib/logstash/inputs/elasticsearch.rb
  logstash-input-elasticsearch.gemspec
  spec/inputs/elasticsearch_spec.rb
Labels: status:needs-review, breaking change

#207 Adding support for custom headers
  docs/index.asciidoc
  lib/logstash/inputs/elasticsearch.rb
  spec/inputs/elasticsearch_spec.rb
Labels: status:changes-requested
